server:
    name: "localhost:8080"

logging:
    level:
        org.springframework.security: TRACE

spring:
    sql:
        init:
            mode: always
    datasource:
        url: jdbc:h2:mem:database
        username: user
        password: password
        driver: org.h2.Driver
